---
title: "figure_instructions"
author: "Anika Neuschulz"
date: "2025-09-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Here are some useful code snippets to improve the appearance of your plots.

```{r pretty_plots}

# Information about expression of multiple genes in all clusters
DotPlot(pbmc_renamed, features = c("your", "chosen", "genes"))

# Information about expression of one gene in all clusters
VlnPlot(pbmc_renamed, features = c("your chosen gene"))

# changing the colours, also see function documentation!
DimPlot(pbmc_renamed, cols = c("your", "colours", "of", "choice"))

# add figure titles and captions (works for other plotting functions as well!)
DimPlot(pbmc_renamed) + labs(title = "Your figure title",
              subtitle = "Your figure subtitle",
              caption = "This figure shows the following...")

# export figure panel
# first save your plot in a variable
plot1 <- DimPlot(pbmc_renamed) + labs(title = "Your figure title",
              subtitle = "Your figure subtitle",
              caption = "This figure shows the following...")
# then export the plot using the ggsave function (from the ggplot package)
# Adapt filename and path to your system. Width and height are given in inches by default, other units of measurement can be specified (see ggsave documentation). Image resolution cal also be specified.
ggsave(plot = plot1, filename = "Path_to_your_plot.png", width = 6, height = 5, dpi = "print")
```
