# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Single-Cell Data Analysis Course @Charité
description: "A beginner-friendly course aimed at MD and PhD students with biomedical background and little to no programming experience."
url: "https://buchauer-lab.github.io"
baseurl: "/charite-sc-data-course"

author:
  name: "Prof. Dr. Lisa Buchauer (Charité) and Dr. Anika Neuschulz (BIH@Charité)"
