# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

# Setup
title: "Single-Cell Data Analysis for Beginners"
tagline: "Course Materials"
description: "Learn single-cell transcriptomics data analysis from scratch"
url: "https://buchauer-.github.io"
baseurl: "/charite-sc-data-course"

# Author
author:
  name: "Lisa Buchauer and Anika Neuschulz"

