# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

# Setup
title: "Single-Cell Data Analysis for Beginners"
tagline: "Course Materials"
description: "Learn single-cell transcriptomics data analysis from scratch"
url: "https://yourusername.github.io"
baseurl: "/your-repository-name"

# Author
author:
  name: "Lisa Buchauer"
  url: "https://twitter.com/libuchauer"

# Jekyll plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/