# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

# Setup
title: "Single-Cell Data Analysis for Beginners"
tagline: ""
description: "A beginner-friendly course aimed at MD and PhD students with biomedical background and little to no programming experience."
url: "https://buchauer-lab.github.io/charite-sc-data-course/"
baseurl: "/"

# Author
author:
  name: "Prof. Dr. Lisa Buchauer and Dr. Anika Neuschulz"

